export class Card {	
	public id: number;
	public parentId: number;
	public orderIndex: number;
	public userId: number;
	public difficultyLevel: number;
	public type: number;
	public hasChild: number;
	public status: number;
	public lastUpdate: string;
	public frontText: string;
	public frontImage: string;
	public frontSound: string;
	public frontVideo: string;
	public frontHint: string;
	public frontLanguage: number;
	public backText: string;
	public backImage: string;
	public backSound: string;
	public backVideo: string;
	public backHint: string;
	public backLanguage: number;
	public backTexts: Array<string>;
	public typeOfWord: string;	
	public multiChoices: Array<string>;	

	constructor () {
		this.id = 0;
		this.parentId = 0;
		this.orderIndex = 0;
		this.userId = 0;
		this.difficultyLevel = 0;
		this.type = 0;
		this.hasChild = 0;
		this.status = 0;
		this.lastUpdate = "18/03/2017";
		this.frontText = "";
		this.frontImage = "";
		this.frontSound = "";
		this.frontVideo = "";
		this.frontHint = "";
		this.frontLanguage = 0;
		this.backText = "";
		this.backImage = "";
		this.backSound = "";
		this.backVideo = "";
		this.backHint = "";
		this.backLanguage = 0;
		this.typeOfWord = "";	
		this.multiChoices = [];
		this.backTexts = [];		
	}
}